# -*- coding: utf-8 -*-
"""test-github-streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ub7DmuX4IyP0cUu2Emk1Q1I8OumpvX6I
"""

import streamlit as st
import yfinance as yf

# Liste des tickers
tickers = ['TTE.PA', 'AIR.PA', 'BNP.PA', 'OR.PA', 'KER.PA']

st.title("Dashboard des performances boursières")

# Sélection d'une entreprise
ticker = st.selectbox("Sélectionnez une entreprise :", tickers)

# Récupération des données
data = yf.download(ticker, start="2019-01-01", end="2023-12-31")

if not data.empty:
    st.line_chart(data['Close'])
else:
    st.error("Aucune donnée disponible.")